apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-app-api.fullname" . }}
  labels:
    app: {{ include "todo-app-api.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "todo-app-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "todo-app-api.name" . }}
    spec:
      containers:
        - name: {{ include "todo-app-api.name" . }}
          image: "{{ .Values.image.domain }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          # Run node with inspect so VS Code can attach to it:
          command: ["node", "--inspect=9229", "dist/main.js"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
