apiVersion: v1
kind: Service
metadata:
  name: {{ include "nestjs-app.fullname" . }}-service
  labels:
    app: {{ include "nestjs-app.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ include "nestjs-app.name" . }}
