replicaCount: 1

image:
  repository: nestjs-app
  pullPolicy: IfNotPresent
  tag: "latest"
  domain: localhost:5000

service:
  type: ClusterIP
  port: 3000

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
